# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import dronecommander_pb2 as dronecommander__pb2


class DroneCommanderStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.register = channel.unary_unary(
                '/dronecommand.DroneCommander/register',
                request_serializer=dronecommander__pb2.RegisterRequest.SerializeToString,
                response_deserializer=dronecommander__pb2.RegisterReply.FromString,
                )
        self.listen_waypoint = channel.unary_stream(
                '/dronecommand.DroneCommander/listen_waypoint',
                request_serializer=dronecommander__pb2.ListenWaypointRequest.SerializeToString,
                response_deserializer=dronecommander__pb2.ListenWaypointReply.FromString,
                )
        self.send_position = channel.unary_unary(
                '/dronecommand.DroneCommander/send_position',
                request_serializer=dronecommander__pb2.SendpositionRequest.SerializeToString,
                response_deserializer=dronecommander__pb2.SendpositionReply.FromString,
                )


class DroneCommanderServicer(object):
    """Missing associated documentation comment in .proto file."""

    def register(self, request, context):
        """Register a new client, anod return success r failure.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def listen_waypoint(self, request, context):
        """Listen to server
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def send_position(self, request, context):
        """Send position of drone
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_DroneCommanderServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'register': grpc.unary_unary_rpc_method_handler(
                    servicer.register,
                    request_deserializer=dronecommander__pb2.RegisterRequest.FromString,
                    response_serializer=dronecommander__pb2.RegisterReply.SerializeToString,
            ),
            'listen_waypoint': grpc.unary_stream_rpc_method_handler(
                    servicer.listen_waypoint,
                    request_deserializer=dronecommander__pb2.ListenWaypointRequest.FromString,
                    response_serializer=dronecommander__pb2.ListenWaypointReply.SerializeToString,
            ),
            'send_position': grpc.unary_unary_rpc_method_handler(
                    servicer.send_position,
                    request_deserializer=dronecommander__pb2.SendpositionRequest.FromString,
                    response_serializer=dronecommander__pb2.SendpositionReply.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'dronecommand.DroneCommander', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class DroneCommander(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def register(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/dronecommand.DroneCommander/register',
            dronecommander__pb2.RegisterRequest.SerializeToString,
            dronecommander__pb2.RegisterReply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def listen_waypoint(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(request, target, '/dronecommand.DroneCommander/listen_waypoint',
            dronecommander__pb2.ListenWaypointRequest.SerializeToString,
            dronecommander__pb2.ListenWaypointReply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def send_position(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/dronecommand.DroneCommander/send_position',
            dronecommander__pb2.SendpositionRequest.SerializeToString,
            dronecommander__pb2.SendpositionReply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
